server:
  port: ${PORT:8080}

spring:
  application:
    name: cv-manager-backend
  datasource:
    spring:
      datasource:
        url: ${SPRING_DATASOURCE_URL:NOT_SET}
        username: ${SPRING_DATASOURCE_USERNAME:NOT_SET}
        password: ${SPRING_DATASOURCE_PASSWORD:NOT_SET}
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

app:
  as-is:
    demo-token-prefix: demo-token
  admin:
    email: admin@example.com
    password: admin123
  cv:
    upload-dir: uploads
