CREATE TABLE cv
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_user_id           BIGINT                                  NOT NULL,
    title                   VARCHAR(255)                            NOT NULL,
    uploaded_html_file_path VARCHAR(500)                            NOT NULL,
    created_at              TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at              TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_cv PRIMARY KEY (id)
);

ALTER TABLE cv
    ADD CONSTRAINT FK_CV_ON_OWNER_USER FOREIGN KEY (owner_user_id) REFERENCES user_account (id);